// Command embeddedwebviewprotocol generates the runtime protocol constants
// shared by the Go message processor and the TypeScript runtime.
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
)

type protocolEntry struct {
	GoName string
	TSName string
}

var objects = []protocolEntry{
	{"callRequest", "Call"},
	{"clipboardRequest", "Clipboard"},
	{"applicationRequest", "Application"},
	{"eventsRequest", "Events"},
	{"contextMenuRequest", "ContextMenu"},
	{"dialogRequest", "Dialog"},
	{"windowRequest", "Window"},
	{"screensRequest", "Screens"},
	{"systemRequest", "System"},
	{"browserRequest", "Browser"},
	{"cancelCallRequest", "CancelCall"},
	{"iosRequest", "IOS"},
	{"androidRequest", "Android"},
	{"embeddedWebViewRequest", "EmbeddedWebView"},
}

var embeddedWebViewMethods = []protocolEntry{
	{"embeddedWebViewCreate", "Create"},
	{"embeddedWebViewDestroy", "Destroy"},
	{"embeddedWebViewSetBounds", "SetBounds"},
	{"embeddedWebViewSetVisible", "SetVisible"},
	{"embeddedWebViewSetZIndex", "SetZIndex"},
	{"embeddedWebViewLoadURL", "LoadURL"},
	{"embeddedWebViewGetURL", "GetURL"},
	{"embeddedWebViewGetTitle", "GetTitle"},
	{"embeddedWebViewIsLoading", "IsLoading"},
	{"embeddedWebViewStop", "Stop"},
	{"embeddedWebViewReload", "Reload"},
	{"embeddedWebViewReloadIgnoringCache", "ReloadIgnoringCache"},
	{"embeddedWebViewCanGoBack", "CanGoBack"},
	{"embeddedWebViewCanGoForward", "CanGoForward"},
	{"embeddedWebViewGoBack", "GoBack"},
	{"embeddedWebViewGoForward", "GoForward"},
	{"embeddedWebViewExecuteJavaScript", "ExecuteJavaScript"},
	{"embeddedWebViewOpenDevTools", "OpenDevTools"},
	{"embeddedWebViewSetZoomFactor", "SetZoomFactor"},
	{"embeddedWebViewGetZoomFactor", "GetZoomFactor"},
	{"embeddedWebViewFocus", "Focus"},
	{"embeddedWebViewIsFocused", "IsFocused"},
}

func main() {
	root, err := findModuleRoot()
	must(err)
	must(writeGo(filepath.Join(root, "pkg/application/messageprocessor_protocol_generated.go")))
	must(writeTypeScript(filepath.Join(root, "internal/runtime/desktop/@wailsio/runtime/src/protocol.generated.ts")))
}

func findModuleRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("go.mod not found")
		}
		dir = parent
	}
}

func writeGo(path string) error {
	var out bytes.Buffer
	out.WriteString("// Code generated by go generate; DO NOT EDIT.\n\npackage application\n\n")
	out.WriteString("const (\n")
	for i, entry := range objects {
		if i == 0 {
			fmt.Fprintf(&out, "\t%s = iota\n", entry.GoName)
		} else {
			fmt.Fprintf(&out, "\t%s\n", entry.GoName)
		}
	}
	out.WriteString(")\n\nvar objectNames = map[int]string{\n")
	for _, entry := range objects {
		name := entry.TSName
		if entry.GoName == "iosRequest" {
			name = "iOS"
		}
		fmt.Fprintf(&out, "\t%s: %q,\n", entry.GoName, name)
	}
	out.WriteString("}\n\nconst (\n")
	for i, entry := range embeddedWebViewMethods {
		if i == 0 {
			fmt.Fprintf(&out, "\t%s = iota\n", entry.GoName)
		} else {
			fmt.Fprintf(&out, "\t%s\n", entry.GoName)
		}
	}
	out.WriteString(")\n\nvar embeddedWebViewMethodNames = map[int]string{\n")
	for _, entry := range embeddedWebViewMethods {
		fmt.Fprintf(&out, "\t%s: %q,\n", entry.GoName, entry.TSName)
	}
	out.WriteString("}\n")
	formatted, err := format.Source(out.Bytes())
	if err != nil {
		return err
	}
	return os.WriteFile(path, formatted, 0o644)
}

func writeTypeScript(path string) error {
	var out bytes.Buffer
	out.WriteString("// Code generated by go generate; DO NOT EDIT.\n\n")
	out.WriteString("export const objectNames = Object.freeze({\n")
	for i, entry := range objects {
		fmt.Fprintf(&out, "    %s: %d,\n", entry.TSName, i)
	}
	out.WriteString("});\n\nexport const embeddedWebViewMethods = Object.freeze({\n")
	for i, entry := range embeddedWebViewMethods {
		fmt.Fprintf(&out, "    %s: %d,\n", entry.TSName, i)
	}
	out.WriteString("});\n")
	return os.WriteFile(path, out.Bytes(), 0o644)
}

func must(err error) {
	if err != nil {
		panic(err)
	}
}
