// Code generated by go generate; DO NOT EDIT.

package application

const (
	callRequest = iota
	clipboardRequest
	applicationRequest
	eventsRequest
	contextMenuRequest
	dialogRequest
	windowRequest
	screensRequest
	systemRequest
	browserRequest
	cancelCallRequest
	iosRequest
	androidRequest
	embeddedWebViewRequest
)

var objectNames = map[int]string{
	callRequest:            "Call",
	clipboardRequest:       "Clipboard",
	applicationRequest:     "Application",
	eventsRequest:          "Events",
	contextMenuRequest:     "ContextMenu",
	dialogRequest:          "Dialog",
	windowRequest:          "Window",
	screensRequest:         "Screens",
	systemRequest:          "System",
	browserRequest:         "Browser",
	cancelCallRequest:      "CancelCall",
	iosRequest:             "iOS",
	androidRequest:         "Android",
	embeddedWebViewRequest: "EmbeddedWebView",
}

const (
	embeddedWebViewCreate = iota
	embeddedWebViewDestroy
	embeddedWebViewSetBounds
	embeddedWebViewSetVisible
	embeddedWebViewSetZIndex
	embeddedWebViewLoadURL
	embeddedWebViewGetURL
	embeddedWebViewGetTitle
	embeddedWebViewIsLoading
	embeddedWebViewStop
	embeddedWebViewReload
	embeddedWebViewReloadIgnoringCache
	embeddedWebViewCanGoBack
	embeddedWebViewCanGoForward
	embeddedWebViewGoBack
	embeddedWebViewGoForward
	embeddedWebViewExecuteJavaScript
	embeddedWebViewOpenDevTools
	embeddedWebViewSetZoomFactor
	embeddedWebViewGetZoomFactor
	embeddedWebViewFocus
	embeddedWebViewIsFocused
)

var embeddedWebViewMethodNames = map[int]string{
	embeddedWebViewCreate:              "Create",
	embeddedWebViewDestroy:             "Destroy",
	embeddedWebViewSetBounds:           "SetBounds",
	embeddedWebViewSetVisible:          "SetVisible",
	embeddedWebViewSetZIndex:           "SetZIndex",
	embeddedWebViewLoadURL:             "LoadURL",
	embeddedWebViewGetURL:              "GetURL",
	embeddedWebViewGetTitle:            "GetTitle",
	embeddedWebViewIsLoading:           "IsLoading",
	embeddedWebViewStop:                "Stop",
	embeddedWebViewReload:              "Reload",
	embeddedWebViewReloadIgnoringCache: "ReloadIgnoringCache",
	embeddedWebViewCanGoBack:           "CanGoBack",
	embeddedWebViewCanGoForward:        "CanGoForward",
	embeddedWebViewGoBack:              "GoBack",
	embeddedWebViewGoForward:           "GoForward",
	embeddedWebViewExecuteJavaScript:   "ExecuteJavaScript",
	embeddedWebViewOpenDevTools:        "OpenDevTools",
	embeddedWebViewSetZoomFactor:       "SetZoomFactor",
	embeddedWebViewGetZoomFactor:       "GetZoomFactor",
	embeddedWebViewFocus:               "Focus",
	embeddedWebViewIsFocused:           "IsFocused",
}
